axpy_data_cost:
	gcc -o bin/axpy_data_cost axpy_data_cost.c vector.c

axpy_normal:
	gcc -o bin/axpy_normal axpy_normal.c vector.c

axpy_random:
	gcc -o bin/axpy_random axpy_random.c vector.c

clean:
	rm -f bin/*